### ISSUE TITLE
[Feature Request] Change the username font color (maybe bring back background colors???)

### ISSUE THREAD

**Issue by kckarnige** [kyrie25/lanyard-profile-readme#19]
Personally, I don't dig the gradient, and I think it'd be nice to add the ability to change the font color or the gradient color to allow users to use solid colors if they want to, _maybe also bring back the ability to change the background color..? 👉👈_

P.S. Themes still work, and light mode breaks stuff

**Comment by kyrie25** [comment]
You can pass in one color value to the gradient parameter for solid username color

```url
https://lanyard.kyrie25.me/api/368399721494216706?gradient=f3f3f3
```
![368399721494216706 (1)](https://github.com/kyrie25/lanyard-profile-readme/assets/77577746/3f861e8c-9643-4a27-a0bc-8ee47af2116e)

Anything from original repository is not removed, including background color

```url
https://lanyard.kyrie25.me/api/368399721494216706?bg=f3f3f3
```
![368399721494216706](https://github.com/kyrie25/lanyard-profile-readme/assets/77577746/ff342523-0c63-4c05-9d34-b223237c866d)


And yeah this isn't meant to be used with light mode in mind but you can change the color variables to get around that, all the activity color parameters are listed in readme. 
E.g.

```url
https://lanyard.kyrie25.me/api/368399721494216706?bg=f3f3f3&theme=light&waveColor=f1c0cf
```
![368399721494216706 (2)](https://github.com/kyrie25/lanyard-profile-readme/assets/77577746/d34096e4-9490-4aba-84f4-ce7f6ce6feb5)

Font color for activity can also be modified exclusively (also listed in Readme)
```url
https://lanyard.kyrie25.me/api/368399721494216706?bg=f3f3f3&theme=light&waveColor=2b2b2b-dark
```

![368399721494216706 (3)](https://github.com/kyrie25/lanyard-profile-readme/assets/77577746/25a315b8-e6ae-4ac2-add1-663377aa41fb)

**Comment by kyrie25** [comment]
Additional dark font on light color tweaks also
![image](https://github.com/kyrie25/lanyard-profile-readme/assets/77577746/155102b8-83a8-4b0e-95e4-2e854a61cedd)

**Comment by kyrie25** [comment]
I think that answers all of your questions! If you have another issue or feature request outside of what you mentioned in this issue then let me know and I'll answer them for you, but for now I'll close the issue since the feature is already added/not removed.

**Comment by kckarnige** [comment]
Thanks a ton ^^
Btw, this is amazing, keep up the good work
