### ISSUE TITLE
[Feature Request] Add support for USRBG

### ISSUE THREAD

**Issue by T3M1N4L** [kyrie25/lanyard-profile-readme#28]
USRBG, if you don't know is a vencord plugin that allows you to have custom banners without nitro, should be supported in this fork! As someone who doesn't have money to pay for nitro and use vencord, it would be really cool to have this ported! If this doesn't come through, I understand lol.

**Comment by kyrie25** [comment]
Done! Check again and see if it works as intended 👌

**Comment by T3M1N4L** [comment]
Wow, it works perfectly!
Thanks!
