### ISSUE TITLE
[Another feature request] Remove the separator line?

### ISSUE THREAD

**Issue by T3M1N4L** [kyrie25/lanyard-profile-readme#30]
![image](https://github.com/user-attachments/assets/7f8be46b-7974-467f-b49e-7dc05821b8fd)
It appears when I'm zoomed out, but when I'm zoomed in it disappears
![image](https://github.com/user-attachments/assets/d6e003fa-e0e7-4ad7-9781-1a3a83dc9508)

The separator was included in the upstream repo, so it would be nice if there was a URL param that could remove all the separators (Yeah there are two, which is a separator that appears on top of the waves, I could recreate the second line by zooming all the way in then zooming out, it seems the second line only appears when the browser hasn't fully rendered, or maybe it's a problem with the waves placement) 
![image](https://github.com/user-attachments/assets/81f40dba-c39d-413b-ba15-1162f622047a)
(it's blurry because I was zooming out)

or maybe it's just a problem with how I set up my url
  <img src="https://lanyard.kyrie25.me/api/861917446750863402?gradient=4fff9e-4fff9e&animated=true&bg=000&useDisplayName=true&showBanner=animated&waveColor=8426ff&waveSpotifyColor=52EF89-light&imgStyle=square&bannerFilter=brightness(0.8)%20blur(2px)&hideDiscrim=false&borderRadius=20px&idleMessage=%3C%2Fbeing+lazy%3E..." height="190vh"/>
</a>

**Comment by T3M1N4L** [comment]
Sorry if this is issue is one that only appears on my side 😅

**Comment by T3M1N4L** [comment]
Now that I look at it more, 
![image](https://github.com/user-attachments/assets/8c9d6e85-58f2-4352-a06e-ef53f4624052)
both of them appear on the highest point the wave reaches and the lowest point of the wave respectively. 

Maybe it's a problem with how the waves render. IDK, but it could be just the separator from the upstream repo.


Edit : It think i figured out the cause for the second separator, it's the translucent wave that is causing it.
![image](https://github.com/user-attachments/assets/f0cd0987-b90c-4efd-b2ed-274dfa7eba57)
I think this can be fixed if you move the translucent wave behind the solid one by changing the z-index.

**Comment by kyrie25** [comment]
This issue only happens because of how WebKit/Safari on iOS renders the card, its stylings and filters for the waves. The image below shows normal rendering on Blink/Chromium-based browsers.
![image](https://github.com/user-attachments/assets/18bd5d16-df1f-4ab5-82a3-c00d9bb78388)

Unfortunately this is unfixable, is very inconsistent to reproduce and only happens for WebKit on iOS.

**Comment by T3M1N4L** [comment]
But I'm using chrome on a Chromebook 💀  and it seems that the waves are behind now, yes this is very inconsistent as sometimes the transparent waves are on the top. Maybe add something that would make it so that it always stays on the bottom. Also is it possible to remove the separator line all together?

**Comment by kyrie25** [comment]
The separators are artifacts, not actual features of the card that I created or have control over.

**Comment by T3M1N4L** [comment]
Wasn't the separator in the upstream too? It seemed to be intentional to me.

**Comment by kyrie25** [comment]
> Wasn't the separator in the upstream too? It seemed to be intentional to me.

It is removed, and please read the actual code before responding with the same question twice if you're still not satisfied with my answer.
https://github.com/kyrie25/lanyard-profile-readme/blob/1d2f0475915402a8bbfe6fa9268b56ca4fcb0fc6/src/renderCard.tsx#L558-L585
