### ISSUE TITLE
Badges with Guild tag issue

### ISSUE THREAD

**Issue by T3M1N4L** [kyrie25/lanyard-profile-readme#32]
I have an issue with the badges where it appears like this :
![image](https://github.com/user-attachments/assets/2d4b21fd-5e36-45c9-811c-6d62a486395e)
even though there is enough space for the badges to be in.

Is there something I'm missing or is this an issue?

This is what I'm using:
  <img src="https://lanyard.kyrie25.me/api/861917446750863402?gradient=4fff9e-4fff9e&animated=true&bg=000&useDisplayName=true&showBanner=animated&waveColor=8426ff&waveSpotifyColor=52EF89-light&imgStyle=square&bannerFilter=brightness(0.8)%20blur(2px)&hideDiscrim=false&borderRadius=20px&idleMessage=%3C%2Fbeing+lazy%3E..." height="190vh"/>
</a>

**Comment by kyrie25** [comment]
What exactly is the issue here?

**Comment by kyrie25** [comment]
Done! Check again and see if the issue persists

**Comment by T3M1N4L** [comment]
It is fixed 👍
