### ISSUE TITLE
[Feature Request] Adding support to Vencord's Decor

### ISSUE THREAD

**Issue by T3M1N4L** [kyrie25/lanyard-profile-readme#33]
The popular discord client mod has a plugin called Decor. This allows users to use their own decorations. Idk if this is possible to be integrated into this project, but if it is it should definitely be added.

**Comment by kyrie25** [comment]
Can you provide the source code to the plugin?

**Comment by T3M1N4L** [comment]
sure - 
https://github.com/Vendicated/Vencord/tree/main/src/plugins/decor

**Comment by kyrie25** [comment]
Done!
