### ISSUE TITLE
Kinda slow

### ISSUE THREAD

**Issue by impishlucy** [kyrie25/lanyard-profile-readme#35]
Idk if its just your fork or lanyard in general, but it takes 2-5 seconds to load.
And someone opening my GH profile likely wont wait that time to see it.
This happens on a selfhosted version too, so either your code or some other api is incredibly slow, i would be very glad if you could have a look into this.

**Comment by kyrie25** [comment]
The card renders within ~300ms to 1s on default configuration, so either your Internet connection is just really slow or you have a lot of large assets in the card (also means your Internet is slow lol)

**Comment by kyrie25** [comment]
In continuation with the previous comment. `Execution duration` = render time + response:
_Your card is the middle one btw, and it only took half a second to render_

<p float="left">
<img src="https://github.com/user-attachments/assets/0d81bcfb-519e-4b93-be2f-c87f025e2227" width="250"/>
<img src="https://github.com/user-attachments/assets/5ee7bfee-dd1a-4e78-959f-d8b9b6ff49a9" width="250"/>
<img src="https://github.com/user-attachments/assets/60ab40ef-8a3c-4620-9776-8d7229af8d0d" width="250"/>
</p>

The rest is handled by GitHub/your ISP, I have no control over that
